arch:
  - amd64
  - arm64

os: linux

services: docker

before_script:
  - wget https://github.com/multiarch/qemu-user-static/releases/download/v5.1.0-7/qemu-aarch64-static
  - chmod +x qemu-aarch64-static

script:
  - docker build -t pipodi/inventory-hunter:latest -f Dockerfile .
  - docker build -t pipodi/inventory-hunter:aarch64 -f Dockerfile-aarch64 .

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push pipodi/inventory-hunter:latest && docker push pipodi/inventory-hunter:aarch64
  on:
    branch: main