language: python

services: docker

before_install:
  - docker build -t pipodi/inventory-hunter .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pipodi/inventory-hunter